# netlify.toml
[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Redirecionamento para a nossa função API
# Todo tráfego para /api/ será direcionado para functions/api.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200